import { ArrowUpRight } from 'lucide-react'
import { useSite } from '../lib/site'
import { Eyebrow, Reveal } from '../components/Blocks'

const extras=[
{date:'18.03.26',type:'Ideas',title:'From handover to high performance: building for the long term.',image:'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=1200&q=85'},
{date:'27.02.26',type:'People',title:'The quiet discipline behind an exceptional project control team.',image:'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=1200&q=85'},
{date:'11.01.26',type:'Perspective',title:'What Mumbai’s changing workplace landscape asks of builders.',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=85'}]
export default function Insights(){const {site}=useSite();const stories=[...site.news,...extras];return <main><section className="insights-hero"><Eyebrow>Insights</Eyebrow><h1>Ideas with their<br/><em>feet on the ground.</em></h1><p>Notes from our people, projects and the changing world of construction.</p></section><section className="insight-feature"><img src="https://images.unsplash.com/photo-1542621334-a254cf47733d?auto=format&fit=crop&w=1800&q=85" alt="Detailed architectural model"/><div><span>Featured perspective · 08.06.26</span><h2>Why preconstruction is the most important part of building well.</h2><p>A better project does not start with a site mobilisation. It starts with the conversations that make the right decisions possible.</p><button onClick={()=>alert('This perspective is being prepared for publication. Please check back soon.')}>Read perspective <ArrowUpRight size={17}/></button></div></section><section className="insight-list">{stories.map((story,i)=><Reveal className="insight-row" key={story.title} delay={i*.03}><span>{story.date}</span><span>{story.type}</span><h3>{story.title}</h3><button onClick={()=>alert('This article is coming soon. Follow Ananta for the latest updates.') } aria-label={`Read ${story.title}`}><ArrowUpRight size={21}/></button></Reveal>)}</section></main>}
